use cooper/event
use cooper/root
use cooper/runtime
use cooper/selection

struct App {
  context: mut runtime::Runtime,
  root: mut root::Root,
}

fn new(exit_on_ctrl_c: Bool?, auto_focus: Bool?, use_mouse: Bool?) App!Error {
  let runtime = try runtime::new_live(exit_on_ctrl_c.or(true), auto_focus.or(true), use_mouse.or(true))
  defer runtime.rollback_construction()
  let root = root::new(runtime)
  runtime.commit_construction()
  runtime.start_signal_monitor()
  Result::ok(App{context: runtime, root: root})
}

impl App {
  fn on_key(handler: fn(mut event::KeyEvent)) fn() {
    self.context.on_key(handler)
  }

  fn on_paste(handler: fn(mut event::PasteEvent)) fn() {
    self.context.on_paste(handler)
  }

  fn terminal_focus() event::TerminalFocus? {
    self.context.terminal_focus()
  }

  fn on_terminal_focus(handler: fn(event::TerminalFocus)) fn() {
    self.context.on_terminal_focus(handler)
  }

  fn selection() selection::Selection? {
    self.context.current_selection()
  }

  fn clear_selection() {
    self.context.clear_selection()
  }

  fn on_selection_change(handler: fn(selection::Selection?)) fn() {
    self.context.on_selection_change(handler)
  }

  fn start() Void!Error {
    self.context.start_live(self.root)
  }

  fn wait() Void!Error {
    self.context.wait_live()
  }

  fn run() Void!Error {
    self.context.run(self.root)
  }

  fn suspend() Void!Error {
    self.context.suspend_live()
  }

  fn resume() Void!Error {
    self.context.resume_live()
  }

  fn destroy() {
    self.context.destroy_live()
  }
}
