use cooper/context
use cooper/core/app_runtime
use cooper/core/event_delivery
use cooper/core/node
use cooper/core/paint
use cooper/style

struct Root {
  node_ref: mut node::Node,
  state_ref: mut app_runtime::State,
}

impl node::Renderable for Root {
  fn node() mut node::Node {
    self.node_ref
  }

  fn mount(ctx: node::MountContext) {}

  fn paint(ctx: mut paint::Context) {}

  fn event(ctx: mut event_delivery::Context) event_delivery::Disposition {
    event_delivery::Disposition::ignored
  }
}

fn new(ctx: mut context::Context, runtime: mut app_runtime::State) mut Root {
  let retained_node = context::internal_state(ctx).create_node(style::new())
  let created = mut Root{node_ref: retained_node, state_ref: runtime}
  retained_node.bind(created)
  retained_node.mark_application_root()
  runtime.bind_root(retained_node)
  created
}

impl Root {
  fn mut add(child: mut node::Renderable, index: Int?) {
    self.node_ref.add(child.node(), index)
  }

  fn mut remove(child: mut node::Renderable) Bool {
    self.node_ref.remove(child.node())
  }

  fn child_count() Int {
    self.node_ref.child_count()
  }
}
