use cooper/box as box_control
use cooper/input as input_control
use cooper/scroll_box as scroll_box_control
use cooper/selection as selection_value
use cooper/text as text_control

type Box = box_control::Box
type Border = box_control::Border
type Input = input_control::Input
type ScrollBox = scroll_box_control::ScrollBox
type Selection = selection_value::Selection
type SelectionRange = selection_value::Range
type Text = text_control::Text
type TextStyle = text_control::TextStyle
type TextWrap = text_control::TextWrap

let box = box_control::new
let input = input_control::new
let scroll_box = scroll_box_control::new
let text = text_control::new
let text_style = text_control::style
